# Generated by Django 3.1.3 on 2020-11-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captive',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
