# Generated by Django 3.1.3 on 2020-11-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpc', '0002_captive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='captive',
            name='comments',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='date_of_aquisition',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='status',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
