# Generated by Django 3.1.3 on 2020-11-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpc', '0003_auto_20201104_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captive',
            old_name='date_of_aquisition',
            new_name='date_of_acquisition',
        ),
    ]
