# Generated by Django 3.1.3 on 2020-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpc', '0004_auto_20201104_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(default=None, max_length=255, null=True)),
                ('stage', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
