# Generated by Django 3.1.3 on 2020-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpc', '0005_statusflags'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=255, null=True)),
                ('to', models.CharField(default=None, max_length=255, null=True)),
                ('cc', models.CharField(default=None, max_length=255, null=True)),
                ('text', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='captive',
            name='batch',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
