# Generated by Django 3.1.3 on 2020-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpc', '0006_auto_20201105_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusflags',
            name='descriptor',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
